name: Rust CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  linux-build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      # Установка Rust
      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      - run: rustup default stable
      # Установка зависимостей для Linux
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-4-dev \
            libgirepository1.0-dev \
            libcairo2-dev \
            libpango1.0-dev \
            build-essential \
            libadwaita-1-dev \
            pkg-config \
            libssl-dev
      # Сборка проекта
      - name: Build project
        run: cargo build --release
      # Загрузка артефакта
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: anixart-app-linux
          path: target/release/anixart-app
  windows-build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      # Установка Rust
      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          echo "$USERPROFILE\.cargo\bin" >> $env:GITHUB_PATH
      - run: rustup default stable
      - run: rustup target add x86_64-pc-windows-msvc
      # Установка предварительно собранного GTK
      - name: Download GTK runtime
        shell: powershell
        run: |
          Invoke-WebRequest -Uri "https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer/releases/download/2023-05-20/gtk-runtime-4.10.0-1-x64.exe" -OutFile gtk-runtime.exe
          Start-Process -Wait -FilePath .\gtk-runtime.exe -ArgumentList "/S", "/D=C:\gtk"
          echo "C:\gtk\bin" >> $env:GITHUB_PATH
          echo "PKG_CONFIG_PATH=C:\gtk\lib\pkgconfig" >> $env:GITHUB_ENV
          echo "GTK_LIB_DIR=C:\gtk\lib" >> $env:GITHUB_ENV
          echo "GTK_INCLUDE_DIR=C:\gtk\include" >> $env:GITHUB_ENV
      # Установка pkg-config
      - name: Install pkg-config
        shell: powershell
        run: |
          Invoke-WebRequest -Uri "https://github.com/pkg-config/pkg-config/releases/download/internal-0.7.1/pkg-config-0.7.1.zip" -OutFile pkg-config.zip
          Expand-Archive -Path pkg-config.zip -DestinationPath .
          echo "$pwd\pkg-config\bin" >> $env:GITHUB_PATH
      # Сборка проекта для Windows
      - name: Build project
        run: cargo build --release --target x86_64-pc-windows-msvc
      # Загрузка артефакта
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: anixart-app-windows.exe
          path: target/x86_64-pc-windows-msvc/release/anixart-app.exe
